return {
	Main = {
		{Text = "Sceleratis/Davey_Bones",	Desc = "Made Adonis & EISS"};
		{Text = "Kohltastrophe (Scripth)",	Desc = "For his help with various things and some code"};
		{Text = "einsteinK",				Desc = "Helped me with some scripting problems early in development and put together the LoadstringParser; Best programmer I know"};
		{Text = "Rerumu (Shining_Diamando)",Desc = "Numerous contributions (Endless stairs, FiOne, Parser, Steampunk theme)"};
		{Text = "Cald_fan", 				Desc = "Community Maintainer & WebPanel Creator & Maintainer"};
		{Text = "joritochip",				Desc = "Community Maintainer & WebPanel Developer"};
		{Text = "Coasterteam",				Desc = "Community Maintainer & Development contributions (Kronos developer)"};
		{Text = "Expertcoderz",				Desc = "Community Maintainer"};
		{Text = "Dimenpsyonal",				Desc = "Community Maintainer"};
	};

	GitHub = {
		{Text = "@GitHub MudockYatho", 		Desc = "Open Source Contributor"};
		{Text = "@GitHub TheCakeChicken", 	Desc = "Open Source Contributor"};
		{Text = "@GitHub NNickey", 			Desc = "Open Source Contributor"};
		{Text = "@GitHub FungusGenerator", 	Desc = "Open Source Contributor"};
		{Text = "@GitHub ItsGJK", 			Desc = "Open Source Contributor"};
		{Text = "@GitHub Kan18", 			Desc = "Open Source Contributor"};
		{Text = "@GitHub Brandon-Beck", 	Desc = "Open Source Contributor"};
		{Text = "@GitHub GeneralScripter", 	Desc = "Open Source Contributor"};
		{Text = "@GitHub moo1210", 			Desc = "Open Source Contributor"};
		{Text = "@GitHub kent911t", 		Desc = "Open Source Contributor"};
		{Text = "@GitHub crywink", 			Desc = "Open Source Contributor"};
		{Text = "@GitHub jaydensar", 		Desc = "Open Source Contributor"};
		{Text = "@GitHub ccuser44",			Desc = "Open Source Contributor"};
		{Text = "@GitHub Awesomewebm", 		Desc = "Open Source Contributor"};
		{Text = "@GitHub TheLegendarySpark",Desc = "Open Source Contributor"};
		{Text = "@GitHub EasternBloxxer",	Desc = "Open Source Contributor"};
		{Text = "@GitHub policetonyR",		Desc = "Open Source Contributor"};
		{Text = "@GitHub enescglyn",		Desc = "Open Source Contributor"};
		{Text = "@GitHub EpicFazbear",		Desc = "Open Source Contributor"};
		{Text = "@GitHub p3tray",			Desc = "Open Source Contributor"};
		{Text = "@GitHub okgabe",			Desc = "Open Source Contributor"};
		{Text = "@GitHub fxeP1",			Desc = "Open Source Contributor"};
		{Text = "@GitHub optimisticside",	Desc = "Open Source Contributor"};
		{Text = "@GitHub NeoInversion",		Desc = "Open Source Contributor"};
		{Text = "@GitHub imskyyc",			Desc = "Open Source Contributor"};
		{Text = "@GitHub LolloDev5123",		Desc = "Open Source Contributor"};
		{Text = "@GitHub happyman090",		Desc = "Open Source Contributor"};
		{Text = "@GitHub GalacticInspired",	Desc = "Open Source Contributor"};
		{Text = "@GitHub flgx16",			Desc = "Open Source Contributor"};
		{Text = "@GitHub DrewBokman",		Desc = "Open Source Contributor"};
		{Text = "@GitHub Kw6m",				Desc = "Open Source Contributor"};
		{Text = "@GitHub chexburger",		Desc = "Open Source Contributor"};
		{Text = "@GitHub TjeerdoBoy112",	Desc = "Open Source Contributor"};
		{Text = "@GitHub Jack5079",			Desc = "Open Source Contributor"};
		{Text = "@GitHub Bulldo344",		Desc = "Open Source Contributor"};
		{Text = "@GitHub evanultra01",		Desc = "Open Source Contributor"};
		{Text = "@GitHub SlipperySpelunky",	Desc = "Open Source Contributor"};
		{Text = "@GitHub c6lvnss",			Desc = "Open Source Contributor"};
		{Text = "@GitHub karl-police",		Desc = "Open Source Contributor"};
		{Text = "@GitHub CommodoreGamer118",Desc = "Open Source Contributor"};
		{Text = "@GitHub spaggos",			Desc = "Open Source Contributor"};
		{Text = "@GitHub jun022222222",		Desc = "Open Source Contributor"};
		{Text = "@GitHub sea4h",			Desc = "Open Source Contributor"};
		{Text = "@GitHub Tj33rd",			Desc = "Open Source Contributor"};
		{Text = "@GitHub DaRealGandhi20",	Desc = "Open Source Contributor"};
		{Text = "@GitHub L8X",				Desc = "Open Source Contributor"};
		{Text = "@GitHub Honzzzox",			Desc = "Open Source Contributor"};
		{Text = "@GitHub Smaltin", 			Desc = "Open Source Contributor"};
		{Text = "@GitHub NoUserSet", 		Desc = "Open Source Contributor"};
		{Text = "@GitHub xvarmkorv2",		Desc = "Open Source Contributor"};
		{Text = "@GitHub Quantify_RBLX",	Desc = "Open Source Contributor"};
		{Text = "@GitHub xhayper",			Desc = "Open Source Contributor"};
		{Text = "@GitHub NoobBucket",		Desc = "Open Source Contributor"};
		{Text = "@GitHub GGshor",			Desc = "Open Source Contributor"};
		{Text = "@GitHub WideManHost",		Desc = "Open Source Contributor"};
		{Text = "@GitHub autodoorsdev",		Desc = "Open Source Contributor"};
		{Text = "@GitHub Lethalitics",		Desc = "Open Source Contributor"};
		{Text = "@GitHub Deniernal354",		Desc = "Open Source Contributor"};
		{Text = "@GitHub RoyallyFlushed",	Desc = "Open Source Contributor"};
		{Text = "@GitHub supercoolspy",		Desc = "Open Source Contributor"};
		{Text = "@GitHub AlexanderDarmody",	Desc = "Open Source Contributor"};
		{Text = "@GitHub watameln",			Desc = "Open Source Contributor"};
		{Text = "@GitHub bigbenster702",	Desc = "Open Source Contributor"};
		{Text = "@GitHub WalkerOfBacon", 	Desc = "Open Source Contributor"};
		{Text = "@GitHub wilsontulus", 		Desc = "Open Source Contributor"};
	};

	Misc = {
		{Text = "Kein-Hong Man",			Desc = "Creator of the Yueliang (Lua bytecode compiler in loadstring module). Also created LuLu VM, the first Lua bytecode interpreter used in Adonis (no longer used)"};
		{Text = "Stravant/JustAPerson",		Desc = "Wrote LBI (no longer used)"};
		{Text = "darkelementallord",		Desc = "Updated some guis"};
		{Text = "TheFurryFish",				Desc = "Gave me some dank ideas like local particles and some loading related things; and helped debug"};
		{Text = "Moistality",				Desc = "Helped with finding and patching vulns"};
		{Text = "GigsD4X/F3X",				Desc = "F3X Building Tool"};
		{Text = "Drezmor",					Desc = "Resize was originally ripped from his ohgals and modified"};
		{Text = "KingKeith55",				Desc = "Provided the Stickify command"};
		{Text = "NickPatella",				Desc = "Made the piano used in the !piano command"};
		{Text = "Raspberry Pi/Raspy_Pi", 	Desc = "Made Dex explorer"};
		{Text = "j1my3p1x",					Desc = "His replication checking idea is what lead to the replication logs"};
		{Text = "Bubby4j",					Desc = "Used their \"Refresh Icon\" image (default theme)"};
		{Text = "meafers",					Desc = "Suggested some stuff"};
		{Text = "Osyris",					Desc = "Wrote 't', an open-source typechecking library"};
		{Text = "buildthomas",				Desc = "Wrote 'MockDataStoreService', an open-source mock DataStoreService replacement library"};
		{Text = "Tiffany352",				Desc = "Wrote an improved base64 implementation"};
		{Text = "",							Desc = ""};
		{Text = "~ :) ~",					Desc = ""};
		{Text = "Donors",					Desc = "Donors keep the wheels turning ;)"};
		{Text = "The Users [You :)]",		Desc = "For using the script and keeping it alive :)"};
		{Text = "Special thanks", 			Desc = "Special thanks to everyone who helped along the way and suggested new ideas!"};
		{Text = "Not listed?",				Desc = "Message Davey_Bones and tell me what you need to be credited for and I'll add you in! (also sorry for missing you the first time)"};
	}
}
